#!/bin/sh

giflibs=`ar xv libgif/libgif.a | cut -d' ' -f3`
tifflibs=`ar xv libtiff/libtiff.a | cut -d' ' -f3`
jpeglibs=`ar xv libjpeg/libjpeg.a | cut -d' ' -f3`
pnglibs=`ar xv libpng-1.2.3/libpng.a | cut -d' ' -f3`

ar -ruv libiomedley.a $tifflibs $jpeglibs $pnglibs $giflibs
